export {default as StartForm} from './SratsForm'
export {default as QuestionPage} from './questionsPage'
export {default as Main} from './main'
export {default as Questions} from './Questions'
export {default as FormInput} from './formInput'
export {default as SelectComp} from './SelectComp'